### PR TITLE
Some script error fixes and minor improvements

### PR DESCRIPTION
**Pull request by Person8880**
- Added option to account for standard deviation when sorting players.
- Made the UTF8 functions fail gracefully by falling back to the standard Lua string library if they encounter invalid UTF8.
- Made some minor improvements to the admin menu.
- Added "CanAlwaysTarget" flag for groups. If set, the group can always be targeted regardless of immunity.
- Added support for wildcards in string argument restrictions.
- Removed a pointless call to GetFileExists (io.open in read mode returns nil if the file doesn't exist) in the NS2 ConfigFileUtility code which was breaking Combat.

### CODE REVIEW

**Comment by GhoulofGSG9** [comment]
Just fyi: the only reason there is a GetFileExists function is to avoid confusing users with errors that get triggered by io.open if the given file does not exists.

**Comment by Person8880** [comment]
What errors? io.open doesn't trigger any errors if it can't find a file (or for any reason at all for that matter), it returns nil and the error message.

**Comment by GhoulofGSG9** [comment]
````
[195.657] ServerUpdate : Error: Unable to open 'random.lua' (usage 0x1)
[20:52:42]Ghoul ran: io.open("random.lua","r")
[20:52:42]Ghoul[49071975] ran command sh_luarun with arguments: io.open("random.lua","r")
Lua run was successful.
````

**Comment by Person8880** [comment]
That doesn't happen for files in the config directory:
```
[19:57:31]Person8880 ran: io.open("config://NonExistantFile.json","r")
[19:57:31]Person8880[54372170] ran command sh_luarun with arguments: io.open("config://NonExistantFile.json","r")
Lua run was successful.
```

**Comment by GhoulofGSG9** [comment]
well seems like that check is redudant as the engine code already checks for config:// :D

**Pull request merged**
