### PR TITLE
Add Czech translation

### PR DESCRIPTION
**Pull request by kparal**
This adds Czech translation.

However, I wasn't able to test it out, because no matter what I do, Shine is always in English, even though the whole NS2 is in Czech. One other person, Chris Stark, complained about the same problem (having a new translation for Shine, but not seeing it), so there's either a bug in code somewhere, or something that should be documented isn't.

Can you try running shine with Czech translation, whether it works for you? And if it does, what does one need to do? I've copied `locale/` dir with new translations to `~/AppData/Roaming/Natural Selection 2/Workshop/m706d242_1461418220`, and ensured NS2 language is set to Czech, but that didn't help.

I'd like to review the changes live before you pull it in, because otherwise I'll likely need to bother you with additional pull request containing translation fixes (too long strings, etc).

### CODE REVIEW

**Comment by Person8880** [comment]
I think the problem is that NS2's `Locale.GetLocale()` doesn't really do what it implies in the documentation. It seems to return some kind of system locale setting rather than the game's.

I've changed it to read the locale option the game seems to be using and it now seems to work. If you take the change of my latest commit and apply it to your local copy, it should work.

**Comment by kparal** [comment]
I applied the patch, but it didn't help. I switched Windows language to Czech, didn't help either. Shine is still in English. What I'm trying is to run a sandbox mode and hit M, where I see "Map Vote", "Surrender", "Client Config", etc options. When I click "Client Config", I see the options in a GUI. I translated all of that, but it's still showing up in English.

Maybe I'm doing something wrong. If you want try to help me debug that, let's do that, otherwise I'm fine with just merging those translations and waiting until they show up in the next Shine version, hopefully showing translated at that time. I'm not convinced it will work, though.

**Comment by Person8880** [comment]
I think you have the wrong language code. It's `csCS`, not `csCZ`.

**Comment by kparal** [comment]
Thank you for spotting this! After renaming all files to `csCS.json`, the translations work now.

However, the locale is supposed to be `csCZ`, it's a bug in NS2. You can see that in this wikipedia example:
https://en.wikipedia.org/wiki/Locale#POSIX_platforms
and also here:
http://www.localeplanet.com/icu/cs-CZ/index.html
http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
and I also see it in Windows PowerShell after running `Get-Culture`.

I'll ask NS2 devs whether they will fix the language code in the game, or whether we should spread the bug into Shine as well.

**Comment by kparal** [comment]
So, they say renaming the locale would purge all translations, and it's difficult to reimport the old translations back to the translation website. So I guess the invalid locale identifier stays.

I have renamed everything to `csCS.json`. Please merge, thank you.

**Comment by Person8880** [comment]
I would hope that all servers receive it immediately when I release. If there are servers that have the mod contained in some super mod then they're doing it wrong, and don't even have permission to do so.

**Pull request merged**
