### PR TITLE
Create ruRU.json

### PR DESCRIPTION
**Pull request by welldotru**

### CODE REVIEW

**Comment by Person8880** [comment]
Firstly, thanks for contributing translations!

Secondly, a question: are you using the GitHub website to add these files? It will be pretty awkward to open lots of individual pull requests. I would look into getting the [GitHub desktop app](https://desktop.github.com/) and cloning your fork using that. That way you can make all the changes on your computer in one go, and submit a single pull request for it after.

Also, could you send the pull request to point towards the `develop` branch please? You can set that when you make the pull request by changing the "base" branch.

**Comment by welldotru** [comment]
Github is new for me. And I can use only web for my githubing.

**Comment by Person8880** [comment]
If you really can only use the website, I believe it's still possible to make all the changes on a single branch if you go to your forked version and add/edit the files there. It should ask you for the branch to add them to, if you add them all to a single branch then submit that branch as a pull-request (to the `develop` base branch) then it'll make things easier.

**Comment by welldotru** [comment]
Yeeep, I almost finish translation, but Github desktop crashing at start. I will try new pull request from another host at home today.
P.S.: May be we will use Discord? "Well" in NS2 channel.

**Pull request closed without merging**
