### PR TITLE
Add support for new dedicated spectator slots (ns2 build 317)

### PR DESCRIPTION
**Pull request by GhoulofGSG9**
Build 317 will add dedicated spectator slots. Those are independent from the normal player slots and can be used additionally to the player slots. Clients using a spectator slot are limited to the spectator team unless they can switch to a free player slot.

To not conflict with this new spectator slot system I propose the following changes:

1. The reserved slot plugin does no longer override the vanilla `CheckConnectionAllowed` event method and instead just checks for available reserved slots.
2. The reserved slot plugin overrides now the global `HasReservedSlotAccess` method which is used to check if the player can switch from a spectator slot to a player slot if the only player slots available are reserved player slots.
3. The vote random plugin doesn't shuffle any client using a dedicated spectator slot into the teams.
4. The reserved slots plugin uses the new Engine API method instead the deprecated `R_S` tag to set the reserved slot count.

### CODE REVIEW

**Comment by Person8880** [comment]
Is it possible to see the code changes for this in the NS2 code?

I don't see how what you've done will prevent players from joining if only reserved slots are free and they don't have access, unless the NS2 code now reads from the `ReservedSlotLimit`.

**Comment by GhoulofGSG9** [comment]
Yes the ns2 code now gets the number of reserved slots via the `Server.GetReservedSlotLimit` API method, which returns the value last set via `Server.SetReservedSlotLimit` or 0.

I posted the diff between the 316 and the spec_slot feature branch at https://gist.github.com/GhoulofGSG9/d2497102db23a1e1168001c8275219de . Additionally you can access the beta build via the Steam Beta branch.

**Comment by Person8880** [comment]
I couldn't see the global function you've referenced. From what I can see the vanilla code doesn't have a way to override its reserved slot access, but it doesn't really need it anyway as the plugin will allow people before it ever reaches that code.

I'll close this as I've solved it in 49213178cb95157fa1db04cef065c88058de2391, but thanks for giving early visibility of this.

**Comment by GhoulofGSG9** [comment]
The reason I added a hook for `GetHasReservedSlotAcces` (lua/ServerAdminCommands.lua:318) is to allow clients using a spectator slot who also have access to a reserved slot to pass the `Gamerules.GetCanJoinPlayingTeam` (lua/Gamerules.lua:128) check.

Passing that check is necessarily for them to be able to switch from a spectator slot to a free reserved slot.

**Comment by Person8880** [comment]
Is the name going to change? You referenced just `HasReservedSlotAccess` while the beta code has `GetHasReservedSlotAcces` (which is missing an s at the end).

**Comment by GhoulofGSG9** [comment]
The name is `GetHasReservedSlotAccess` in the latest beta version and won't change anymore.

**Pull request closed without merging**
